language: objective-c
rvm:
  - 2.2.2
before_install:
        - brew update
        - brew install xctool || true
        - brew upgrade xctool || true
        - brew install carthage || true
        - brew upgrade carthage || true
        - gem install cocoapods --pre || true
        - export LC_ALL="en_US.UTF-8"
script: rake test
